### ISSUE TITLE
Proper Release

### ISSUE THREAD

**Issue by seb45tian** [Bernsai/GaussianProcessModelInference#1]
Hi Fabian,

would it be possible to create a proper release for version 2.0.0 (and upcoming versions) on github and/or pypi? This way it's much easier to create reproducible builds and enable scientists to create reproducible results. Otherwise people would have to keep track of specific commits.

Same goes for https://github.com/Bernsai/GaussianProcessFundamentals

Many thanks and kind regards from the WWU HPC Team
Sebastian

**Comment by Bernsai** [comment]
Hi Sebastian,

a proper release for both repositories should be available via Github and
an appropriate flag for the respective commits.

Best regards,
Fabian

Am Mi., 11. Aug. 2021 um 13:18 Uhr schrieb seb45tian <
***@***.***>:
